---
title: "Market Basket"
output:
  html_document:
    df_print: paged
---

```{r}
library(tidyverse)
library(readxl)
library(knitr)
library(ggplot2)
library(lubridate)
library(arules)
library(arulesViz)
library(plyr)
```

```{r}
retail <- read_excel('Online_retail.xlsx')
retail <- retail[complete.cases(retail), ]
retail %>% mutate(Description = as.factor(Description))
retail %>% mutate(Country = as.factor(Country))
retail$Date <- as.Date(retail$InvoiceDate)
retail$Time <- format(retail$InvoiceDate,"%H:%M:%S")
retail$InvoiceNo <- as.numeric(as.character(retail$InvoiceNo))
glimpse(retail)
```

```{r}

retail$Time <- as.factor(retail$Time)
retail %>%  
  ggplot(aes(x=Time)) +
  geom_histogram(stat="count",fill="indianred")

```

```{r}
detach("package:plyr", unload=TRUE)

retail %>% 
  group_by(InvoiceNo) %>% 
  summarize(n_items = mean(Quantity)) %>%
  ggplot(aes(x=n_items))+
  geom_histogram(fill="indianred", bins = 100000) + 
  geom_rug()+
  coord_cartesian(xlim=c(0,80))
```

```{r}
tmp = retail %>% 
  group_by(StockCode, Description) %>% 
  summarize(count = n()) %>% 
  arrange(desc(count))

tmp %>% 
  ggplot(aes(x=reorder(Description,count), y=count))+
  geom_bar(stat="identity",fill="indian red")+
  coord_flip()


```
```{r}
retail_sorted <- retail[order(retail$CustomerID),]
library(plyr)
itemList <- ddply(retail,c("CustomerID","Date"), 
                       function(df1)paste(df1$Description, 
                       collapse = ","))
```

```{r}
itemList$CustomerID <- NULL
itemList$Date <- NULL
colnames(itemList) <- c("items")
```

```{r}
write.csv(itemList,"market_basket.csv", quote = FALSE, row.names = TRUE)
```

```{r}
tr <- read.transactions('market_basket.csv', format = 'basket', sep=',')
summary(tr)
```
```{r}
itemFrequencyPlot(tr, topN=20, type='absolute')
```

```{r}
rules <- apriori(tr, parameter = list(supp=0.001, conf=0.8))
rules <- sort(rules, by='confidence', decreasing = TRUE)
summary(rules)
```
```{r}
inspect(rules[1:10])
```

```{r}
topRules <- rules[1:10]
plot(topRules)
```
```{r}
plot(topRules, method="graph")
```
```{r}
plot(topRules, method = "grouped")
```

